spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insuranceVehicles
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
    port: 8081
